package com.example.rule_engine.entity;

public enum RuleType {
    VELOCITY_1M,
    AMOUNT_1H,
    MICRO_TX_BURST_1M,
    SMALL_VALUE_SPREAD_24H,
    RECEIVER_INBOUND_SPIKE_24H,
    SENDER_RECEIVER_REPEAT_24H,
    OVERSEAS_HIGH_AMOUNT,
    NIGHT_NEW_DEVICE,
    ABSOLUTE_HIGH_AMOUNT,
    CROSS_BORDER_AMOUNT_TIER,
    CROSS_BORDER_HIGH_AMOUNT,
    NEW_RECEIVER_HIGH_AMOUNT,
    FIRST_TIME_RECEIVER_HIGH_AMOUNT
}
